server:
  port: 7070
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/royturpo/DAD-0501.git # ruta del repositorio git
          searchPaths: config-data
          default-label: registry-server

  security:
    user:
      name: root
      password: 123456